services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: php-design-patterns-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: php-design-patterns-server
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d